### ISSUE TITLE
Crash ContentfullDelivery request/response when try to use contentfullManagement apis in same project

### ISSUE THREAD

**Issue by arpanCode** [contentful/contentful.objc#62] opened 2016-09-12 05:39 UTC
Hi, 
I have beed using contentfulDelivery api for last 3 weeks they were working fine. 
Today when i am integrating CMAClient in project and creating shared instance, after integrating management client,  every time delivery api calls  getting crash while deliveryReponse

2016-09-09 16:04:21.074 Obino[12655:1408269] *** Assertion failure in -[CDARequestOperationManager fetchArrayAtURLPath:parameters:success:failure:], /Projects/Obino/Obino/Pods/ContentfulDeliveryAPI/Code/CDARequestOperationManager.m:74
2016-09-09 16:04:21.084 Obino[12655:1408269] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Response object needs to be an array.'
Please help  it's very critical situation..

**Comment by neonichu** [comment] 2016-09-13 14:09
Duplicate of contentful/contentful-management.objc#14, let's discuss it over there.

**Closed by neonichu** 2016-09-13 14:09 UTC
