### ISSUE TITLE
Not Runing in iOS Device

### ISSUE THREAD

**Issue by AshishPatel48** [contentful/contentful.objc#88] opened 2017-09-12 12:37 UTC
In Select device only show Mac , How can i run in iOS Device simulator..?

**Comment by loudmouth** [comment] 2017-09-12 15:06
Hi @AshishPatel48 , unless I'm missing some key information here—this is not an issue with the SDK as far as I can tell. You must configure your Xcode project as an iOS project in order for iOS simulators to show up as build destinations. You can also open the "Devices" window in Xcode to edit what simulators show up.

**Comment by AshishPatel48** [comment] 2017-09-13 05:43
Can you please share any link for iOS SWIFT project sample.?

**Comment by AshishPatel48** [comment] 2017-09-13 12:18
Hi One Last Question Please Help


I Have total data :-


<__NSArrayI 0x17410be20>(
CDAEntry 50ae1TT60M6q6AAa8kqmIS with fields:{
    attributeName = Texture;
},
CDAEntry 2Q7q4vWbxS0aeuqAScUCiw with fields:{
    attributeName = Thickness;
},
CDAEntry 2NZQB0AwDYqQ04USokIsmu with fields:{
    attributeName = "Texture and Strength";
},
CDAEntry 4pya6IjfbiYymUS0YgswGK with fields:{
    attributeName = "Size of the Nail";
},
CDAEntry 3yzrL2lOtiGqeqoiiAkUSW with fields:{
    attributeName = "Complete Nail Destruction";
},
CDAEntry 3Xsuhi8CR2qAkuC0IOYY4S with fields:{
    attributeName = "Nutrition-Associated Lesions";
},
CDAEntry 35KVAjlakwmoAK20q8mme0 with fields:{
    attributeName = "Processes around the Nails";
},
CDAEntry 5sJl4KVArKaA0sSkqsWu22 with fields:{
    attributeName = Color;
},
CDAEntry 15Mc71PPQsM0wyyU4GGA4y with fields:{
    attributeName = Elasticity;
},
CDAEntry 1uME840oLu2y0wWSmqmYyW with fields:{
    attributeName = "Hair Distribution/ Character";
},
CDAEntry 3gPLANr3pYwWM2yu482YIQ with fields:{
    attributeName = Shape;
},
CDAEntry 86Yd5oZnfqA8k8co2g4cE with fields:{
    attributeName = "Growth Pattern and Nail Surface Changes";
},
CDAEntry 41CRI9fABqSmG82wCkYI6s with fields:{
    attributeName = Hydration;
},
CDAEntry 4fL69zh0OcqouqamumAiUq with fields:{
    attributeName = "Color Changes or Color Patterns (lines/spots)";
},
CDAEntry 4IbEGWNgq4e60c86SOsIS with fields:{
    attributeName = Temperature;
}
)

I want to filter data which  referenceBodyPart id = f5T4tJHFIssMgEMQwyQ2O

{
    attributeName = Texture;
    referenceBodyPart = "CDAEntry f5T4tJHFIssMgEMQwyQ2O with fields:{\n    bodyPartName = Skin;\n}";
}

**Comment by AshishPatel48** [comment] 2017-09-13 13:27
How to filter data in iOS objective C?

**Comment by loudmouth** [comment] 2017-09-19 12:27
Hi @AshishPatel48, apologies for the delayed response, i was on vacation last week.

Filtering for an entry which references a body part with id `f5T4tJHFIssMgEMQwyQ2O` would requires you to specify the content type of the item being referenced, and also specify the source item that holds the reference. See [Contentful's documentation for Searching on References](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references) for more info.

In your case, your query dictionary would look like the following

```objective-c
NSDictionary *queryParameters = @{
@"content_type": @"<SOURCE_CONTENT_TYPE_ID>",
@"fields.referenceBodyPart.sys.contentType.sys.id":@"<DESTINATION_CONTENT_TYPE_ID>",
@"fields.referenceBodyPart.fields.companyName"= @"f5T4tJHFIssMgEMQwyQ2O"
};
[self.client fetchEntriesMatching:queryParameters success: ...
...
```

**Comment by loudmouth** [comment] 2017-09-19 12:31
I'm closing this ticket for now as it's a usage related question and not a bug or issue with the SDK. Also, feel free to reachout at support@contentful.com if you are having trouble with usage in the future.

**Closed by loudmouth** 2017-09-19 12:31 UTC

**Comment by AshishPatel48** [comment] 2017-09-26 12:24
Thank you very much for your support.

Need one more help, Can u please let me know how to get multi value para like

sys.id":@"xyz" 
But how to het 2 id data like 
sys.id = "xyz , abs"

**Comment by AshishPatel48** [comment] 2017-09-26 12:33
"sys.id.likes[all]" : [@"79svHaHUYgM06CwcmE2cQm",@"5F1elxU9MWCCqeIe60smYM"]

I am trying this way bit didn't work

**Comment by loudmouth** [comment] 2017-09-27 15:14
Hey @AshishPatel48 your query should not include the "likes":

```objective-c
@{
  @"sys.id[all]" : @[@"79svHaHUYgM06CwcmE2cQm",@"5F1elxU9MWCCqeIe60smYM"]
};

I am trying this way bit didn't work
```

**Comment by AshishPatel48** [comment] 2017-09-28 04:54
Okey Thank you very much but I got solution
@{
  @"sys.id[in]" : @[@"79svHaHUYgM06CwcmE2cQm",@"5F1elxU9MWCCqeIe60smYM"]
};
